### ISSUE TITLE
Event timing not saving properly in MxMTimeline

### ISSUE THREAD

**Issue by Avindr** [Avindr/MxM-IssueTracking#101]
![image](https://user-images.githubusercontent.com/29056263/107896360-c4506700-6f81-11eb-89d6-5468567e95df.png)

**Comment by azevedco** [comment]
I'm Xinnova from your Discord channel, just providing your requested info.
Unity Version: 2019.4.2f1
In your script MxMTaggingWindow.cs, go to your function DrawMotionMatchingData(Rect a_areaRect).  Where you do your change checks for the float fields and where the buttons labelled "|" are pressed, I put in the following line after the values were updated:

`EditorUtility.SetDirty(m_targetMxMAnim as ScriptableObject);`

I had done some research regarding ScriptableObjects losing changes when Unity is restarted and they mentioned that as the solution, which looks to be fixing my problem.  I noticed that when I Pre-Process the data, those timing values are slightly modified again but it didn't look like it reverts the values but sets the to something slightly different.
Let me know if you need any additional info.
Cheers.

**Comment by azevedco** [comment]
Just want to provide a quick example of how I modified the Wind-up section in your script.
```
EditorGUILayout.BeginHorizontal();
                    EditorGUI.BeginChangeCheck();
                    float windup = EditorGUILayout.FloatField(new GUIContent("Wind-up"), m_selectEvent.Windup);
                    if (EditorGUI.EndChangeCheck())
                    {
                        Undo.RecordObject(m_targetMxMAnim as ScriptableObject, "Change Event Windup");
                        m_selectEvent.Windup = windup;

                        if (m_selectEvent.Windup < 0f)
                            m_selectEvent.Windup = 0f;

                        EditorUtility.SetDirty(m_targetMxMAnim as ScriptableObject);
                    }

                    if (GUILayout.Button("|", GUILayout.Width(22f)))
                    {
                        Undo.RecordObject(m_targetMxMAnim as ScriptableObject, "Change Event Windup");
                        m_selectEvent.Windup = Mathf.Clamp(m_selectEvent.EventTime - m_selectEvent.Actions[0] -
                            m_curTime, 0f, m_selectEvent.EventTime - m_selectEvent.Actions[0]);

                        if (m_selectEvent.Windup < 0f)
                            m_selectEvent.Windup = 0f;

                        EditorUtility.SetDirty(m_targetMxMAnim as ScriptableObject);
                    }
```

**Comment by Avindr** [comment]
Thanks for this. I've added this in and it will be coming in a Hotfix to 2.2.8 on the Discord channel.
