### ISSUE TITLE
updating to 2.2.8 stops eventlayers from working

### ISSUE THREAD

**Issue by PLATYROO** [Avindr/MxM-IssueTracking#103]
eventlayers stops working after updating to 2.2.8. on 2020.1.8f1, works fine on 2.2.7 after hotfix
<3<3<3

**Comment by Avindr** [comment]
In which way does it stop working. Are the events simply not being called?

It's kinda strange I don't believe I touched the system at all. I'll check it out.

**Comment by PLATYROO** [comment]
Yeh they’re just not being called. realised might’ve been something I did
when I updated old api. If ya can’t see it on your end don’t stress about
it *¯\_(ツ)_/¯*

**Comment by Avindr** [comment]
All good, haven't had a chance to check yet, just wanted to clarify when I get around to it.

**Comment by PLATYROO** [comment]
it was totally my screw up after all, all working now
