### ISSUE TITLE
Warp Module data resetting 2.2.8

### ISSUE THREAD

**Issue by Broudy001** [Avindr/MxM-IssueTracking#104]
Warp Module data not saving

- Created a Warp Module from the MxM Right Click menu
- Change the values as appropriate
- Click off the Asset and back onto, the values are reset back to the default
- Checked other module assets, they are ok
- Tested on a couple of devices so doesn't look like a unity installation issue

**Comment by Avindr** [comment]
Cheers, I'll check it out. Could you let me know your Unity version just in case.

**Comment by Broudy001** [comment]
It was on 2020.2.5f.  Haven't gone up from there as I've heard there are other issues with .6f

**Comment by Avindr** [comment]
Fixed for MxM v2.9 releasing 19/03/2021
