### ISSUE TITLE
Mecanim parameters reset when there is a change in animations within MxM

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#108]
Using a mecanim animator with a single bool parameter and animation and a standard MxM setup for a human character (ie similar to the tutorial series setup)

When the mecanim animator is blended in from MxM using BlendOutController and the parameter is set to true, when there is no movement from MxM (ie character remains in the same idle pose), the parameter can be set to true with no issues. When there is any movement from MxM (ie, press forward key), even though MxM is still blended out, all parameters within mecanim are reset.
If there is no movement from MxM and the character remains in the same loop in the background, the mecanim parameter can safely be set and it will remain the value it was set.

If the character is in an idle state with 1 or more sub idles, the character is looping through the base idle when the mxm is blended out and mecanim takes over, a mecanim parameter is set to true.  As soon as the mxm idle switches to the secondary idle, the mecanim parameter is reset.

As well as the parameters being reset. lets say we have 2 mecanim states, walk and run (both transitions have no exit time).  When the parameter is set to 0, it will go to the walk state and play a walk animation.  When the parameter is at 1, mecanim will transition into a run state and play a run animation.  When we set the parameter to 1, we enter the run animation, we then supply MxM with some movement, this will reset the mecanim parameters to 0 and we should transition back into the walk state, however mecanim seems to transition but the animation playing on the character in game view is still the running animation, yet the mecanim graph shows the walk animation playing.

**Comment by Avindr** [comment]
Thanks for the report, this is a known issue caused by a Unity bug in versions 2019.4+

Please see original issue here for current workaround: https://github.com/Avindr/MxM-IssueTracking/issues/100

I've been looking into potential ways to avoid this bug completely but can't promise anything at this point.
