### ISSUE TITLE
NullReferenceException when adding animation clips in Unity 2020.3

### ISSUE THREAD

**Issue by mazeTheory-kieran** [Avindr/MxM-IssueTracking#110]
Unity 2020.3.0f1
MxM version 2.2.8

Recently upgraded to Unity 2020.3.0f1, and actual motion matching/animation seems to work just fine.
However, when attempting to add new animation clips to an MxM Animation Module, I get the following error message:

`NullReferenceException: SerializedObject of SerializedProperty has been Disposed.
UnityEditor.SerializedProperty.CopyInternal () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.SerializedProperty.Copy () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.SerializedProperty.GetArrayElementAtIndex (System.Int32 index) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
MxMEditor.AnimationModuleInspector.CreateNewAnimationCompositeFromDrag (UnityEngine.AnimationClip a_clip, System.Int32 a_categoryId) (at Assets/Plugins/MotionMatching/Code/MxM/Editor/Inspectors/AnimationModuleInspector.cs:616)
MxMEditor.AnimationModuleInspector.DragDropComposites (UnityEngine.Rect a_dropRect, System.Int32 a_categoryId) (at Assets/Plugins/MotionMatching/Code/MxM/Editor/Inspectors/AnimationModuleInspector.cs:420)
MxMEditor.AnimationModuleInspector.OnInspectorGUI () (at Assets/Plugins/MotionMatching/Code/MxM/Editor/Inspectors/AnimationModuleInspector.cs:212)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)`

If you need more info, please let me know

**Comment by Avindr** [comment]
Hi, 

This is a bug relating to all Unity version v2020.2.6+

I have implemented a workaround and it will be available in MxM v2.9 which will release today.
