### ISSUE TITLE
v2.2.9 compilation error CS0200

### ISSUE THREAD

**Issue by CrocoRabbit** [Avindr/MxM-IssueTracking#111]
Using Unity 2020.2.5f new errors appear after the v2.2.9 update

![image](https://user-images.githubusercontent.com/80267550/111752686-af2b6880-889e-11eb-87c6-50096fee826d.png)

MxMPreProcessDataInspector.cs (1381,29) & (1651,13)

m_data.LastSaveDirectory  and m_data.LastSavedAnimData "cannot be assigned to -- it is read only"

**Comment by Avindr** [comment]
dangit. Sorry about that. I'll fix it asap

**Comment by Avindr** [comment]
This is now fixed and the new build has been uploaded. 

Discord - Use the same link as previous, the upload has been updated

Unity Asset Store - Hotfix has been submitted and should be available soon.
