### ISSUE TITLE
MxMEventLayers does not support match required tags

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#112]
The event layers does not have support for matching required tags for BeginEvent like regular MxMAnimator events support.  It will improve flexibility and consistency of events.   For example currently I'm using tag based equip/unequip and event layers wont deal with that with out.

MxM 2.2.9

**Comment by Avindr** [comment]
This has been updated for MxM2.2.10 coming soon.

MxMEventLayers will now respect RequireTags and FavourTags and PoseFavour in an identical manner to normal events.
