### ISSUE TITLE
MxM Timeline Curve editor, edit text and add key icon hard to read while in dark mode

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#114]
![image](https://user-images.githubusercontent.com/324463/112050605-f50b5980-8b48-11eb-9aee-8ba90dfea9d5.png)

When you are editing the name of the a curve it can unreadable while editing the name.  I attached an image for reference. It's slightly better on the darker lines.   The add new curve plus key button is also pretty hard to see.  The diamond shape you could see but I was searching for the '+' key button mentioned in the manual needed to squint really hard to see it 😅 

Unity 2019.4.21f1
Dark theme

**Comment by Avindr** [comment]
This has been fixed for the next update.
