### ISSUE TITLE
Angular Warping interface inconsistent and contains errors.

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#124]
Debugging strange behavior in error warping lead me to an error and some inconsistencies with angular error warping interface.  This is probably related to the introduction of the WarpModule.  

TL:DR;
1. AngularErrorWarpThreshold is assigning the wrong variable. Should be assigning m_angularErrorWarpThreshold
2. SetAngularErrorWarping never sets m_angularErrorWarpMinAngleThreshold

The actual problem I was having was that m_angularErrorWarpThreshold was set to an unreasonably high number (360) and caused the error warping not to trigger.

Looking at where it gets assigned and who uses it I found some irregularities.  

The m_angularErrorWarpThreshold  variable is only set via the inspector or using the SetAngularErrorWarping method. 

The property AngularErrorWarpThreshold is not setting m_angularErrorWarpThreshold but is setting m_angularErrorWarpAngleThreshold instead.

This leads to the unfortunate issue that SetWarpOverride method is actually assigning m_overrideWarpSettings.DistanceThreshold to m_angularErrorWarpAngleThreshold via AngularErrorWarpThreshold.  Which is then followed by setting m_angularErrorWarpAngleThreshold again to m_overrideWarpSettings.AngleRange.y;

This means that when assigning a warp module to the MxMAnimator m_angularErrorWarpThreshold is never set.

The last irregularity is that the SetAngularErrorWarping method never sets m_angularErrorWarpMinAngleThreshold like the SetWarpOverride does. 

In other news.  I like the Warp Module.  Makes setting those variables much nicer.
Happy Days.

**Comment by Avindr** [comment]
Cheers, I'll fix this up for the next update.

**Comment by Avindr** [comment]
This is fixed for MxMv2.2.10 coming soon.
