### ISSUE TITLE
Event markers cannot be deleted.

### ISSUE THREAD

**Issue by tadilj** [Avindr/MxM-IssueTracking#131]
・Unity Version:
2021.1.16f1 personal Mac Editor

・MxM Version:
2.2.10

・What is happenening?:
When I try to delete an event marker, it shows "Delete".
When I select "Delete", "Delete" appears again.
Even if I select the newly displayed "Delete". The event marker will not be deleted.

・When does it happen?
It happens all the time.

・Can it be easily reproduced?
Yes

・If so how?
When you use MxM Timeline.

Thank you.
---
anagrammer

**Comment by Avindr** [comment]
I have managed to reproduce this issue and will attempt to fix it for the next update.

In the meantime, events can still be deleted by selecting them and pressing the 'delete' key.

**Comment by Avindr** [comment]
This has now been fixed for the next update. 

Thank you for reporting.
