### ISSUE TITLE
RuntimeMxMConstructor.cs contains "using UnityEditor.SceneManagement;", which may cause build failures.

### ISSUE THREAD

**Issue by tadilj** [Avindr/MxM-IssueTracking#132]
・Unity Version:
2021.1.16f1 personal Mac Editor

・MxM Version:
2.2.10

・What is happenening?:
RuntimeMxMConstructor.cs contains "using UnityEditor.SceneManagement;", which may cause build failures.
SceneManagement;" that is not being used should be removed.

・When does it happen?
It happens the iOS Build.

・Can it be easily reproduced?
Yes

Thank you.

---
anagrammer

**Comment by Avindr** [comment]
This has been removed for the next update.
