### ISSUE TITLE
MotionCurveData: Mismatch in number of curves and curve handles.

### ISSUE THREAD

**Issue by csunseri** [Avindr/MxM-IssueTracking#134]
We are getting the attached error on the initial launch of our scene after upgrading from MxM 2.2.8 to 2.2.10. The error clears itself after restarting the game scene. We have tried reprocessing. This is on Unity Version 2020.3.15

![image](https://user-images.githubusercontent.com/90046493/132007444-b94cfc70-7640-439f-b050-3078a4512d6e.png)

![image](https://user-images.githubusercontent.com/90046493/132007459-c92d1646-445b-44ff-97a5-e64a2656786e.png)

**Comment by Avindr** [comment]
Thank you for the report. I will investigate the issue further and get back to you with my findings.

**Comment by csunseri** [comment]
Thanks Ken. Not sure if this is helpful but I was able to get the error to stop by adding a new curve, then deleting it, and I also clicked update in the animation curve panel. Not sure what cleared the error... either way, the old error is no longer showing but I am now getting the error attached below. 

![image](https://user-images.githubusercontent.com/90046493/132268945-898b269e-cd5b-4c34-b2e3-5480a947e8b2.png)
![image](https://user-images.githubusercontent.com/90046493/132268950-4413abee-7ee7-4439-a2b3-335c8e899773.png)

**Comment by Avindr** [comment]
While I wasn't able to reproduce this myself. I have placed additional null checks on the Curves and CurveHandles variables to prevent this in future. 

It may only occur in certain circumstances where no curve is being used.

This fix will be included in the next available update.
