### ISSUE TITLE
Footstep Tags sometimes don't trigger or trigger too quickly in succession.

### ISSUE THREAD

**Issue by Avindr** [Avindr/MxM-IssueTracking#135]
Requires further investigation. May be related to current weighting of animations.

**Comment by Avindr** [comment]
**Bug Fix:**
After reviewing the code for triggering footstep tags a bug was found and corrected on line 80 of MxMAnimator_Tags.cs. This bug would cause the tag track to be sampled at the incorrect time if the dominant animation is a looping animation. This fix will be included in the next update but can be modified as follows if the fix is needed now:

![image](https://user-images.githubusercontent.com/29056263/140847718-0dedfd17-30ec-4a0a-b317-d268e6328b66.png)

**Other Info**
Footstep tags are always triggered based on the 'DominantAnimationChannel'. This is the animation with the highest weight in the motion matching stack. Due to the nature of motion matching, this dominant animation can change frequently, meaning that new footstep tags can be triggered in quick succession in some circumstances. The solution is to have a minimum timing between footsteps to reduce excessive repetition. 

An option to set minimum footstep frequency will be added to the system to help prevent this. However, this logic can be performed by the user themselves upon receiving the footstep callback if need be.

**Comment by Avindr** [comment]
A new option for 'Min Footstep Interval' has been added to the MxMAnimator as follows: 

![image](https://user-images.githubusercontent.com/29056263/140852901-1b16eebc-ca9e-41cc-a3ed-dc1fdd7b624b.png)

This minimum interval could be changed at runtime for different locomotion speeds / types by modifying the property 'MaxFootstepInterval as shown below:

![image](https://user-images.githubusercontent.com/29056263/140853052-6e9dfef6-b0bd-4eaf-9387-74b647ead073.png)

These improvements will be included in the next update.

**Comment by Avindr** [comment]
Closing this for now as I have received no further information regarding the issue. Can be re-opened if issues still occur down the line.

**Comment by audonator** [comment]
Looks like _animTime_ wasn't updated correctly. Should update _animTime_ before range is calculated:)

![image](https://user-images.githubusercontent.com/6140305/144384015-de1c03e1-01fa-4097-a2af-e6847430dc1e.png)

**Comment by Avindr** [comment]
Yes I forgot to change the order sorry. I've fixed this and pushed an update for it. I'm uploading an update to the Unity store now too.
