### ISSUE TITLE
Event rotation warping will overshoot

### ISSUE THREAD

**Issue by audonator** [Avindr/MxM-IssueTracking#136]
Function MxMAnimator.ComputeLinearEventRotationWarping should probably return the clamped rotation. Return value is used when applying root motion.

Also "remainingWarp" should probably be the delta angle.

Reproducible by setting up the MxMTIPExtension to trigger events -> there will often be a frame with a completely different rotation nearing the end of the turn.

<img width="640" alt="ComputeLinearEventRotationWarping" src="https://user-images.githubusercontent.com/6140305/136154404-5d80c175-ad21-4a07-a0d6-a6385229edd8.png">

**Comment by Avindr** [comment]
Thank you for your input. The suggested changes have been made and will be included in the next update coming mid November.
