### ISSUE TITLE
Input scaling doesn't include upper bound

### ISSUE THREAD

**Issue by audonator** [Avindr/MxM-IssueTracking#137]
MxMInputProfile.GetInputScale should probably include the upper bound when scaling an input vector -> a value of e.g. 1 will not be scaled unless the input profile is set up with max input range > 1 (example input profiles have entries from 0 to 1).

<img width="544" alt="GetInputScale" src="https://user-images.githubusercontent.com/6140305/136155306-2fea94f9-35fd-459f-80d1-42734d1f1496.png">

**Comment by Avindr** [comment]
Thank you for the suggestion. This change has been made and will be included in the next update coming mid November
