### ISSUE TITLE
Reports of Idle Traits not functioning properly

### ISSUE THREAD

**Issue by Avindr** [Avindr/MxM-IssueTracking#138]
Requires further investigation and reproduction.

**Comment by audonator** [comment]
The MxMPreProcessor doesn't populate the actual names of idle traits. Changing line 142 to the following should fix it:
![image](https://user-images.githubusercontent.com/6140305/142198407-88d74f75-aa27-4768-8eab-1763dd3969d3.png)

**Comment by Avindr** [comment]
Thank you, I was about to look into this one. This will save me some time. Cheers

**Comment by Avindr** [comment]
This fix has now been implemented and will be included in the next build coming soon.
