### ISSUE TITLE
MxMAnimatorSpeedSync file doesn't match with class name, plus doesn't have namespace in it

### ISSUE THREAD

**Issue by merpheus-dev** [Avindr/MxM-IssueTracking#139]
Its not a problem to change the class name, but it would be good to fix the class name or the file name, because in current situation, you can't add or find the MxMAnimatorSpeedSync component to a gameobject without checking the code.

**Comment by Avindr** [comment]
Cheers for pointing that out. I've changed the filename to match the class name (MxMAnimatorPlaybackSync for the next update.
