### ISSUE TITLE
Composite category settings throws exception

### ISSUE THREAD

**Issue by PerunCreativeMK** [Avindr/MxM-IssueTracking#148]
Hi,
I tried to work with modules but when I click to composite category settings it throws a NullReferenceException at CompositeCategorySettingsWindow.cs:178 (m_moduleData.TagNames is null). I also found at least one other exception in general MxM workflow (GUI Error: Invalid GUILayout state in MxMTaggingWindow view. Verify that all layout Begin/End calls match
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) when I double click to animation in MXM-Preprocessor) but I do not know if I should submit these errors here because I currently work on unity 2021.2.0b13 (still beta and officially there is problem even with installing Jobs etc.) 

MxM version: 2.2.12

**Comment by Avindr** [comment]
Hi, thanks for the information, I will look into this

**Comment by Avindr** [comment]
After further investigation I found that there was indeed a bug in CompositeCategorySettingsWindow.cs.

I have fixed the bug and it will be available with the next update. In the meantime, this error can be worked around by adding a Tag Naming Module to the MxMAnimation Module as shown below:

![image](https://user-images.githubusercontent.com/29056263/149448238-085a5361-1424-4899-9fef-b53c5ed8c84b.png)

This will prevent the error from occurring in the meantime.

As for the second error you found with GUILayout in MxMTaggingWindow. I wasn't able to reproduce this one on Unity 2020.3.25f1. It's possible this is an issue with the current beta version. If you run into this error again in a release version of Unity > 2020.3.25f1 feel free to submit another issue for that  with reproduction steps. 

Thanks for the information.

**Comment by MnogoZnaet** [comment]
Have the same MxMTaggingWindow issue in Unity 2022.2.0b16

**Comment by MnogoZnaet** [comment]
The error seems to gone for me, after I found that 
`private void DrawDataArea()`
has 

```
GUILayout.BeginArea(areaRect);
EditorGUILayout.BeginVertical();

 //The play toolbar
 EditorGUILayout.BeginHorizontal(EditorStyles.toolbar, GUILayout.ExpandWidth(false));
```
but 
`EndVertical`

doesn't call at the end

**Comment by Avindr** [comment]
This has now been resolved in the tagging window as well. Thanks for reporting.
