### ISSUE TITLE
Trying to blend in an invalid layer. Out of range. Aborting

### ISSUE THREAD

**Issue by p8rivier** [Avindr/MxM-IssueTracking#151]
When I follow the video 'Motion Matching for Unity: Tutorial - Blend Space layers', I follow precisely the same procedure,  but when I test play the scene, it still only one Animation Layer Mixer!

Here it is the official error message :

MxMAnimator: Trying to blend in an invalid layer. Out of range. Aborting
UnityEngine.Debug:LogWarning (object)
MxM.MxMAnimator:BlendInLayer (int,single,single) (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator_Layers.cs:196)
MxMGameplay.ExampleDemoInput:Start () (at Assets/Plugins/MotionMatching/Demo/Code/ExampleDemoInput.cs:75)

Thanks in advance!

**Comment by Avindr** [comment]
Thank you I will investigate and fix as soon as I can.

**Comment by Avindr** [comment]
I think this is related to issue #152 which caused layers to not be created in some circumstances.

I included an update package file in response to that issue. I recommend Importing that patch to your project and it should fix it. The changes will be included in future updates. 

If the issue still persists then I'm happy to re-open this and investigate further.
