### ISSUE TITLE
Cannot enable gravity in MxMAnimationDecoupler

### ISSUE THREAD

**Issue by PerunCreativeMK** [Avindr/MxM-IssueTracking#153]
Hi,
I found a small bug in MxMAnimationDecoupler script. 
`public bool EnableGravity { get { return m_enableGravity; } set { m_enableGravity = false; } } `
(false insted of value)
I fixed it in my code but it is anoying to do it after every update to newer version or reimport ( I always forget to change it :) ).

**Comment by Avindr** [comment]
Thanks for the info. I will include this change in the next update.

**Comment by Avindr** [comment]
Cheers, I've made this change and will include it with further updates going forward.
