### ISSUE TITLE
I get an error when I click the play button in the Unity Editor

### ISSUE THREAD

**Issue by tadilj** [Avindr/MxM-IssueTracking#165]
Unity: 2021.3.6f1 Mac
MxM: Version 2.2.14
PlayableGraph Visualizer: 0.2.1-Preview.3

I get an next error when I click the play button in the Unity Editor

ArgumentNullException: Value cannot be null.
Parameter name: The Playable is null.
UnityEngine.Playables.PlayableHandle.Pause () (at <6ffc9e3cf18747d6970df6c4b6fa016d>:0)
UnityEngine.Playables.PlayableExtensions.Pause[U] (U playable) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Director/PlayableExtensions.cs:72)
MxM.MxMAnimator.Pause () (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator.cs:2927)
MxM.MxMAnimator.OnDisable () (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator.cs:411)

**Comment by Avindr** [comment]
I'll look into this. Is this with the latest version on the Unity Asset Store?

**Comment by tadilj** [comment]
It appears that PlayableGraphVisualizer (Preview) is now required instead of optional.

**Comment by Avindr** [comment]
> 

That's really strange. It shouldn't be required at all. I'm wondering if I accidentally included it in one of the files with auto refactor but I can't see it anywhere.

**Comment by Avindr** [comment]
This appears to have been fixed in a previous update.
