### ISSUE TITLE
GetCurveValue regression in MxM 2.2.14

### ISSUE THREAD

**Issue by keithgolden** [Avindr/MxM-IssueTracking#167]
GetCurveValue() isn't working for anything except  EMxMAnimtype.Clip. The apparent cause is that the necessary runtime initialization in MotionCurveData.InitializeCurvesRuntime() is only applied to MxmAnimData.ClipsData. Adding the following lines to InitializeNativeData() seems to help:

```
            foreach (BlendClipData blendClipData in BlendClips)
            {
                blendClipData.CurveData.InitializeCurvesRuntime();
            }
            foreach (CompositeData compositesClipData in Composites)
            {
                compositesClipData.CurveData.InitializeCurvesRuntime();
            }
```
I'm not sure whether this works for Composites or just for BlendClips, since I was still seeing a case of CurveHandleRemap == null in MotionCurveData for at least one Composite, something I haven't looked into. I also haven't looked into BlendSpaces, since I don't have any.

**Comment by Avindr** [comment]
This has now been fixed
