### ISSUE TITLE
MxMTaggingWindow GUILayout invalid program exception

### ISSUE THREAD

**Issue by 2Hadolphin** [Avindr/MxM-IssueTracking#168]
There are two EditorGUILayout.EndVertical() mess up with EditorGUILayout.EndHorizontal() inside MxMTaggingWindow.DrawDataArea();

1.After //The play toolbar & //The Event Toolbar
2.Before the last GUILayout.EndArea();

**Comment by Avindr** [comment]
This has been fixed via a different issue report.
