### ISSUE TITLE
Feature Request Apply Playable IK to AnimationClipPlayable

### ISSUE THREAD

**Issue by 2Hadolphin** [Avindr/MxM-IssueTracking#169]
Unity routine phase of OnAnimatorIK() only invoke when animation playable set playable IK as true.
 

MxMAnimator.cs
line 952: (add) clipPlayable.SetApplyPlayableIK(m_applyPlayableIK);
line 980 : (add) clipPlayable.SetApplyPlayableIK(m_applyPlayableIK);
line 1080 : (add) clipPlayable.SetApplyPlayableIK(m_applyPlayableIK);
line 2229: (add) clipPlayable.SetApplyPlayableIK(m_applyPlayableIK);

**Comment by 2Hadolphin** [comment]
I seems missed other playable IK setup in parital mxm animator.

Require a AnimationClipPlayable creation delegate,
so we can setup playable config like PlayableIK by custom usage.

**Comment by Avindr** [comment]
I have added an 'ApplyPlayableIK' option to the MxMAnimator inspector which will SetApplyPlayableIK on the clipplayables.

Sorry, I do not understand what you are trying to say in your second comment. I will close this issue for now, if you have more details open a new issue with further information.

**Comment by LudiKha** [comment]
There are some places where it's not enabled, most notably for the Idle clips.
