### ISSUE TITLE
MxMFootstepDetector produces Nullref exceptions if toes are not defined in the mecanim rig

### ISSUE THREAD

**Issue by tatoforever** [Avindr/MxM-IssueTracking#171]
Unity Version: 2019.4.40f1
MxM Version: 2.2.14
What is happening?
- MxMFootstepDetector produces Nullref exceptions if toes bones are not defined in the mecanim rig (humanoid rigs)
When does it happen?
- When using the "Auto Detect FootSteps" in the MxM Timeline
Can it be easily reproduced? If so how?
- Open any animation in the MxM Timeline, use a rig that has no toes defined in the mecanim muscle editor and hit the "Auto Detect FootSteps" button, you'll get the exception
Screenshots? (if useful)
- The exceptions happens in these two lines (103 & 104):
![image](https://user-images.githubusercontent.com/23645290/208975461-81186af8-8acb-4cc0-aad1-3eebcb25dbf5.png)
Workaround or fix? Yes.
- If no toes are detected, then use the footbones instead:
![image](https://user-images.githubusercontent.com/23645290/208973008-5e9549c0-508d-477d-ae95-db380abdbc10.png)
Example working:
![image](https://user-images.githubusercontent.com/23645290/208973108-3d4ee874-79ea-47b8-a2d5-684be314506f.png)

**Comment by Avindr** [comment]
This has now been implemented. Thank you for the report.
