### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by Junkdog9** [Avindr/MxM-IssueTracking#177]
unity Version 2021.3.14f1
MxM Version 2.2.14
Errors
right after i import/download
![Screenshot 2023-01-22 155558](https://user-images.githubusercontent.com/123332971/213943841-c849d390-0f0e-4dd4-9f15-b4ccf6cb0e9a.png)

**Comment by Avindr** [comment]
Hi,

Please follow the instructions in the Quick start guide and user manual to download the relevant unity packages required for the asset to function.
