### ISSUE TITLE
Idle Set Animation can't be previewed

### ISSUE THREAD

**Issue by Chokingen** [Avindr/MxM-IssueTracking#178]
When I double-click the animations in Idle Sets, the GUI Error pops out.
And the animation in Idle Sets can't be previewed in the MxM Timeline window.
But the other animations can be previewed and configured normally.
Running under Unity 2021.3.23.
![image](https://github.com/Avindr/MxM-IssueTracking/assets/89328861/01576ee5-b924-4ed3-864a-edd5277d184d)
![image](https://github.com/Avindr/MxM-IssueTracking/assets/89328861/a5e96dc2-869f-4863-8070-93f6c56d58e9)
The packages of my project are as below.
![image](https://github.com/Avindr/MxM-IssueTracking/assets/89328861/8814e738-ec55-4f05-ba23-e41691c6c7c9)

**Comment by tadilj** [comment]
This also happens with Animation Data when MxMAnimationModule is used.
Unity 2021.3.23f1 Personal
Mac Editor.

**Comment by ShuFengYingt** [comment]
Face the same problem with Unity 2021.3.10f1c2.

**Comment by Shaun-Fong** [comment]
This error doesn't actually affect the game, but it's still annoying ....
If you want to fix, go `MotionMatching/Code/MxM/Editor/EditorWindows/MxMAnimationIdleSetWindow.cs` line 252 and 253
```
EditorGUILayout.BeginVertical();
EditorGUILayout.BeginHorizontal(EditorStyles.toolbar, GUILayout.Height(20f), GUILayout.ExpandWidth(true));
```
Just add 
```
EditorGUILayout.EndHorizontal();
EditorGUILayout.EndVertical();
```
after line 325.
Like this
![image](https://github.com/Avindr/MxM-IssueTracking/assets/16713354/120fd5d1-51a2-4468-92ed-84d92969f495)

**Comment by Shaun-Fong** [comment]
Another editor side error happen when double click BlendShape animations, go `MotionMatching\Code\MxM\Editor\EditorWindows\MxMTaggingWindow.cs` line 3042
`m_targetMxMAnim.EventMarkers` should check if it is null.
![image](https://github.com/Avindr/MxM-IssueTracking/assets/16713354/7d9c7c5a-c6b8-45ab-a639-140b9698f4d3)

**Comment by Avindr** [comment]
These issues have been fixed and are included in the update coming this week
