### ISSUE TITLE
GUI doesn't line up well with new Unity interface in Unity 2019.3+

### ISSUE THREAD

**Issue by Avindr** [Avindr/MxM-IssueTracking#2]
Line spacing has changed with Unity 2019.3x resulting in a number of GUI elements from MxM not fitting as nicely as they did in previous versions.

A pass is required to modify the GUI spacing on a pre / post 'new interface basis'

![image](https://user-images.githubusercontent.com/29056263/70879910-e7e0f000-2012-11ea-94a5-841626c1ffe1.png)

![image](https://user-images.githubusercontent.com/29056263/70879949-03e49180-2013-11ea-84e5-9592a6d47a98.png)

![image](https://user-images.githubusercontent.com/29056263/70879978-27a7d780-2013-11ea-8516-3586fa8f4153.png)

![image](https://user-images.githubusercontent.com/29056263/70880003-3abaa780-2013-11ea-83ed-86945e4fa8b1.png)

![image](https://user-images.githubusercontent.com/29056263/70880039-50c86800-2013-11ea-89e3-e473462dc4b1.png)

**Comment by Avindr** [comment]
![image](https://user-images.githubusercontent.com/29056263/70880069-6473ce80-2013-11ea-9224-d140ecc58550.png)

**Comment by AndrewChirtoca** [comment]
![mxm_timeline](https://user-images.githubusercontent.com/12412700/70914793-5d53bd00-2021-11ea-813c-9fc9aff18f58.JPG)
![mxm_debugger](https://user-images.githubusercontent.com/12412700/70914800-60e74400-2021-11ea-906d-456554052c09.JPG)

**Comment by Avindr** [comment]
The majority of these issues have been fixed in a first pass on 2019.3 GUI. This will be available in v2.03.

Issue will remain open until the remainder of issues are completed (mostly the debugger)

**Comment by Avindr** [comment]
Additional fixes to MxMInputProfile and EventNamingModule inspectors for 2019.3+ UI

**Comment by Avindr** [comment]
Closing due to the generic nature of this. Majority if not all UI issues have been fixed for release versions of Unity.

Any further GUI issues can be reported separately on a case by case basis.
