### ISSUE TITLE
Floating point bug in MxMPreProcessor.ProcessIdleSets()

### ISSUE THREAD

**Issue by ottoGithub** [Avindr/MxM-IssueTracking#4]
Unity Version: 2019.2.14f1
MxM Version: beta1.91b

I have a 2-second length idle clip and m_data.PoseInterval = 0.1 
when execute the loop below:
for (float clipTime = 0; clipTime < idleSet.PrimaryClip.length; clipTime += m_data.PoseInterval)
when clipTime = 1.9, the loop exited.  //pose range: [0 - 19]

however when in MxMPreProcessor.GeneratePoseSequencing(), it will lead a different result because of the floating point precision.
int posesToEnd = Mathf.FloorToInt((clip.length - pose.Time) / m_data.PoseInterval);
                        pose.LastPoseId = pose.PoseId + posesToEnd; // LastPoseId = 20
the variable pose.LastPoseId will be out of range.

**Comment by Avindr** [comment]
Fixed for MxM v2.04 release. Cheers

This also led to a few other fixes for a similar issue in the pre-processor where it was possible that some poses may never be created in the first place.
