### ISSUE TITLE
MxM character occasionally warping to 0, 0, 0 on events where warping is disabled

### ISSUE THREAD

**Issue by Avindr** [Avindr/MxM-IssueTracking#43]
Potential bug in event warping code that allows a warp to 0, 0, 0 on rare edge cases.

Requires investigation and confirmation that it is actually a bug within MxM.

**Comment by Avindr** [comment]
Cannot reproduce. 

Event warping code has been reviewed and there does not seem to be any possible instance of warping being activated when it is not set in the event definition or manually at runtime.

Additional checks have been put in place to ensure warping cannot happen if not desired. This will be included in the next update.

If this is happening to you please check the following:
1. EventDefinition has positional warping set to 'None'
2. NumContactsToWarp is set to 0
3. Ensure the EventDefinition you are using at runtime is in fact the same one you are looking at in the inspector
4. Ensure that you are not modifying the 'MotionWarpType' in the EventDefinition at runtime
5. Ensure you are only using the BeginEvent(EventDefinition a_definition); version of the begin event functions.

A final redundancy measure would be to provide these event with 'Disable Warping' tags in the timeline for their duration if this seems to be happening.
![image](https://user-images.githubusercontent.com/29056263/87494563-b0165580-c692-11ea-8d9c-b020e3dc0906.png)

**Comment by Avindr** [comment]
The issue is still occurring for some users and appears to be related to the KCC integration as no errors could be found in the warping code. The investigation continues. If you do encounter this issue could you please leave any additional information here.

**Comment by tadilj** [comment]
In my case, it's not KCC, it's ECM.

**Comment by Avindr** [comment]
After a very long time I have still not seen this particular issue reproduce. I have reviewed the event warping system several times and put in place guards to stop any potential un-expected warping.

For now I will close this issue. If anyone encounters this issue and is able to provide instructions or a project for reproduction I will re-open the issue.
