### ISSUE TITLE
VaultDetector can incorrectly detect StepUp on flat surface

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#47]
I found an issue in the VaultDetector that was causing a Jump vault with out an apparent reason while on flat surface.  It was particularily easy to replicate while vaulting up on the large platform in the back with the box on top.  After triggering a StepUp vault to get up to the platform and keeping the forward velocity it will often trigger an additional StepUp vault.  This is can happen on most surfaces.

Fortunately I also tracked down the reason. In VaultShapeAnalysis I  found the VaultProfile Rise to be incorrectly offset by the DetectProbeRadius radius.  This happens to be the same as the minRise on the Jump StepUp definition so depending on rounding the vault can trigger.

The root cause is that the rise uses the (maxRise - a_rayHit.distance)  to compute the rise.  The problem here is that the RaycastHit.distance is not the distance to the hit point but the distance the sphere travels before it hits. So in a straight line you will end up with a DetectProbeRadius offset.   The solution I used was to use (a_rayHit.point.y - charPos.y).  

Bonus issue:
There is another issue there as well which is that the lastPoint variable is never updated while analyzing the rays.  The assignment is in the wrong scope outside of the for loop.  Pretty sure this improved the hand placement in the vault overs.

Love this system, very impressed.
Just scratching the surface here still 😄 

Thanks for all the fish

**Comment by Avindr** [comment]
Thanks for going into detail. I'll check it out and fix these issues.

_**Note:** The Vault Detector probably has a lot of edge cases where it won't work. I only developed it to a level required to demonstrate Motion Matching events and contact warping in the MxMDemo. I'll fix issues like this but just be aware that it isn't a production ready vaulting system. Someday it would be nice to improve it to a level where it could stand on it's own but it's currently not a high priority._

**Comment by Avindr** [comment]
Thanks for all the information provided. While I wasn't able to reproduce the behaviour you described, the code issues you pointed out were spot on. 

I've fixed both issues (including bonus) and this will be included in the next release of MxM. Cheers
