### ISSUE TITLE
FootIK enabled by default

### ISSUE THREAD

**Issue by VanDraven** [Avindr/MxM-IssueTracking#49]
Unity version : 2019.4.5f1
MxM version : 2.2.4

MxMAnimator seems to enable Mecanim's footik on layer 0.

Steps to reproduce :
- Create two identical characters, one animated by MxM, the other with Mecanim only
- Use only one standing animation for both characters (check the animation on the preview window to be sure there is a difference when IK is activated)
- Hit play, then the MxM character is acting exactly like the mecanim one when you check footIK on the animation state.

**Comment by Avindr** [comment]
The Foot IK that is applied to animation playables is for Unity's Humanoid re-targeting system. The humanoid re-targeting system uses IK to fix up the feet at runtime after re-targeting. Essentially this IK become part of the clip itself, it should affect anything else. 

Turning this foot IK off permanently will adversely affect many people animations. Therefore, an option will be added to the MxMAnimator to choose whether to use the FootIK or not. 

Additionally, the layer system will have have a options in the API to set layers to use IK or not.

**Comment by Avindr** [comment]
Will be deployed alongside the hotfix to 2.2.5
