### ISSUE TITLE
Unable to delete composite category from animation module unless it's the last one.

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#50]
I find that I'm unable to delete a Composite collection from the Animation Data section of a MxM Animation Module unless it is the last one in the set.  The workaround is to move the category to the bottom using the Up/Down buttons.  That gets tedious pretty fast especially since the categories can't be collapsed.

The same issue seems to affect the main pre-processor.

Reproduction Steps:
I exported the Standalone animation set to a module was splitting them into two collections, movement and sword.  
- Press the Delete option for a category not at the bottom of the list
- you get the warning pop up (STOP! WAIT! HOLD UP!) and accept Yes
- observe that the category is still present in the Animation Data (The actual Issue)
- move the category to the bottom using the Down
- press Delete again and accept the pop up with Yes
- observer that the category has been removed as expected

Error in Console when failing to deleting:
EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Avindr** [comment]
Thanks for the info, will investigate further.

**Comment by Avindr** [comment]
Unable to replicate in MxM development version of Unity. Could you please let me know which version you are having this issue in?

**Comment by freyzor** [comment]
I'm using 2.2.5.  I can no longer reproduce this. I just re-tested it both in the regular pre-processor and a module.  Even tried exporting a new module and try there.  Seems to work fine now.   I must have gotten my editor into a weird state somehow.  Feel free to close this.

**Comment by Avindr** [comment]
Thanks for confirming. Yeh Unity's old IMGUI can be funny some times. A shame the new UI system didn't come out earlier.
