### ISSUE TITLE
OnEventContactReached not invoked if there is only one contact point

### ISSUE THREAD

**Issue by dai-xi** [Avindr/MxM-IssueTracking#52]
Unity Version : 2019.4.7f1
MxM Version: 2.2.5
If there is only one contact point in an event, the line "m_onEventContactReached.Invoke(m_curEventContactIndex)" In file  MxMAnimator_Events.cs will not be reached.

Thanks.

**Comment by Avindr** [comment]
This has been resolved for the next release (either 2.2.6 or Hotfix).

In the meantime, if you would like the fix early, please see MxMAnimator_Events.cs and add the highlighted line of code as shown below:

![image](https://user-images.githubusercontent.com/29056263/90357946-f139c500-e097-11ea-8ef9-21c60905b580.png)
