### ISSUE TITLE
Events are unable to take advantage of tags forcing users to use separate events for similar actions.

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#53]
When setting up events for similar actions, like for example a kick while in sword stance and a kick in a pistol stance.  We are unable to use the same event type since the MxM is unable to tell which version of the event to use that fits the stance.  This can lead to a rapid proliferation of event types.  So for each stance you might end up needing a separate set of events for essentially the same events.

It would be preferable IMO to be able to use the tag system already in place for motion matching to help pick the appropriate events as well.   So you can use required tags to tell the difference between a dash in normal stance, sword stance or weather the stance supports it a all.

A complication might be when you want to use the same event in several different stances.  Perhaps you could have a list of tag requirements that can then match several different situations using the same event.

**Comment by Avindr** [comment]
I will probably implement this as an optional bool when calling an event. 

Something like:

`void BeginEvent(MxMEventDefinition a_eventDef, bool a_useTags=false);`

That way it won't change the existing behaviour in anyone's existing projects unless they desire to add flag to check tags.

**Comment by freyzor** [comment]
Another usecase for tagging events would be the Turn In Place Extension.  It would benefit from picking events based on tags. That way you can differentiate between TIP while in different states such as pistol aiming and rifle aiming.  Given they use the same TIP animation ranges.  What is probably more salable though is to add required tags to the TIP definitions them selves so the extension can have different granularity per state/stance. That would still leave us with a lot of events per stance. /rant off

**Comment by Avindr** [comment]
Yes, this is planned for next update. Matching tags will be an optional checkbox on the MxMEventDefinitions. The 'DoNotUse' tag will be excluded from the check as all Event usually need to be marked as DoNotUse so they don't play at runtime.

**Comment by Avindr** [comment]
This has now been implemented and is working. Will be included with v2.2.6. Simply check the highlighted box on your MxMEventDefinition and the event system will respect require tags for that event. 

![image](https://user-images.githubusercontent.com/29056263/91794929-a30fee80-ec5f-11ea-9171-42f8eb9fd8a2.png)

Continue to mark your events as DoNotUse, this particular tag (only) will be ignored when resolving tags for events.
