### ISSUE TITLE
Can't cancel preview when setting joint

### ISSUE THREAD

**Issue by transat** [Avindr/MxM-IssueTracking#63]
When clicking on Set To Joint in the timeline and then clicking on cancel, the operation goes ahead anyway and opens up the preview scene even though the main scene needed to be saved first.

**Comment by Avindr** [comment]
This is a new thing with newer versions of Unity. The genius' decided to change the order of operations on dialog boxes so they run parallel... meaning the operation continues regardless of choice. 

I'll see what I can do about it.

**Comment by Avindr** [comment]
Please note that alpha and beta versions of Unity are not supported so if this bug does not occur in the latest full release of Unity it will not be fixed unless it is still a problem once the beta / alpha versions fully release.

**Comment by transat** [comment]
For sure. If it's a beta / alpha issue then no need to do a permanent fix yet. A bandaid could be to change the text modal to warn users to click on Save and not Cancel if they're on an unsupported version, lest they lose unsaved changes. But it's not a biggie as I'm probably one of very few users using MxM with an alpha / beta.

**Comment by Avindr** [comment]
Ah I think I mis-understood this one. Yes there's definitely something not working here even in 2018.4. I'll try fix this one for v2.2.6

**Comment by Avindr** [comment]
Confirmed fixed in all preview cases. Fix will be shipping with v2.2.6
