### ISSUE TITLE
Input Profile Input range FloatFields too small

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#80]
MxMInputProfileInspector.cs
The float fields for spMin & spMax are too small.  we can only see the value to 1 decimal place.  Often in the tutorials, values specified below a range of 0.1 decimal places are used, ie Practical Tutorial Part 2: Character setup @ 15:20

I'd suggest a value of 39f for both the spMin & spMax Widths, this gives us 3 decimal places.

ie
(Line 70): spMin.floatValue = EditorGUILayout.FloatField(spMin.floatValue, GUILayout.Width(39f));
(Line 83): spMax.floatValue = EditorGUILayout.FloatField(spMax.floatValue, GUILayout.Width(39f));

**Comment by Avindr** [comment]
Hi,

I've made the suggested changed for min max float fiels on the MxMInputProfile Inspector.

This will be available in MxM v2.2.8.

Cheers
