### ISSUE TITLE
Animation Module - Section Cog.  None of the Apply buttons work.

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#81]
In the Animation Module, we have sections such as Turn In Place, Composite Walk Anims, Run anims etc.  Each section has a cog. when this is selected a popup box appears with options for tags.

The three buttons available to us, Apply Require Tags, Apply Favour Tags and Apply All.  All buttons do not work, nothing is applied to any animation in the section.

The work around for this is to use the global animation cog to apply settings to all animations within the module.
![Untitled](https://user-images.githubusercontent.com/2862900/101970765-4b9cf980-3c24-11eb-9c22-b273e2655ec2.png)

In the screen shot above. I have already applied the composite category setting for the section, selected one of the animations within this section and brought up the composite category settings again for comparison.  We can see that after being applied, the animation shows that no favour tag was applied.

I have tested with the other options available within the composite category settings and none seem to be applied, regardless of what is set or what button is pressed.

**Comment by jrmacgill** [comment]
Just ran into this doing step 2 of the quick start tutorial.
Did a bit of digging:
Line 238 of CompositeCategorySettingsWindow in ApplySettings reads:
            if (spCompositeList != null) return;
It should (probably) read:
            if (spCompositeList == null) return;

This worked for me (YMMV).  Note that open MxM Anim Config windows don't refresh, but if you move to another anim and back it should show the correct values.

**Comment by Avindr** [comment]
> Just ran into this doing step 2 of the quick start tutorial.
> Did a bit of digging:
> Line 238 of CompositeCategorySettingsWindow in ApplySettings reads:
> if (spCompositeList != null) return;
> It should (probably) read:
> if (spCompositeList == null) return;
> 
> This worked for me (YMMV). Note that open MxM Anim Config windows don't refresh, but if you move to another anim and back it should show the correct values.

Cheers for that

**Comment by Avindr** [comment]
This has been fixed and will be included in MxM v 2.2.8

**Comment by Craigjw** [comment]
v2.2.8 Still doesn't work.

**Comment by Craigjw** [comment]
I did some more testing on this and it seems that it partially works, however when trying to change a tag, the original tag will not be changed.  ie if I set a section to Walk, then later decide that I want them to be Run, the Walk tag will not get overriden by the newer Run tag.

**Comment by Avindr** [comment]
Thanks for the update. I'll check it out further.

**Comment by Avindr** [comment]
I've managed to get it to update the MxMAnimConfig but it still requires you to at least click on / focus on the MxMAnimConfig for the values to update. 

Unity doesn't seem to want to repaint a window that doesn't have focus and I've searched long through the API for a way to force a repaint of a separate window but without any luck. At least now you shouldn't have to close and re-open the window.
