### ISSUE TITLE
MxM Debugger - Lower Pane has data offscreen

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#86]
The Debugger lower pane has data that I can't view as it's offscreen, I can't resize the panel big enough to view the data.

Can scroll bars be added please.

**Comment by Avindr** [comment]
Hi,

Yes I can add this at some point. I see you have already added it to the
issue tracker. Thanks for that

Regards,

Ken Claassen

**Comment by Craigjw** [comment]
The Current Pose window needs a vertical scroll, while a horizontal scroll might be useful to some people.

The Animator State window, would benefit from a horizontal scroll, while a vertical scroll might be useful to someone using a single screen.

The Layers window, I'm not sure if this is missing anything, some of the info is obscured by the limits of the containing box area.  I haven't used it yet, so don't really know about it's use.

While I have multiple screens, I can just place the debug window on another screen, which I usually do, however for anyone with a single screen, both the Current Pose and Animator State windows are going to be an issue for them.  

I've added a screen shot of the Layers window to show what I mean.

![scroll3](https://user-images.githubusercontent.com/2862900/102229688-f858ce80-3ee3-11eb-8cb9-98e15054609b.png)

**Comment by Avindr** [comment]
Scroll views have been implemented for all long columns in the debugger window now. Available in MxM  v2.2.8
