### ISSUE TITLE
Documentation - Suggested case scenarios and settings for Anim config

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#89]
In Cowboy tutorial 5 ~40:00, you describe some suggested settings for cut clips in the Anim config window such as Extrapolate, Flatten trajectory, runtime splicing etc.  Some example suggestions for clip scenarios would be helpful in the documentation for our reference.

By this I mean a list of case scenarios, such as which type of clips would benefit from runtime splicing and which might not and also when to use them etc. I'm guessing a more specific example of this might be the Extrapolation option, it might be more useful for clips walking in an arc, but less useful for clips walking in a straight line.

**Comment by Avindr** [comment]
I think Section 3.1 of the documentation explains this pretty well. There isn't a long list of cases to be honest. 

Each setting has a detailed explanation and it's primary use case. I don't think more is necessary here.
