### ISSUE TITLE
Provided script causes error at "Gameplay Walkthrough Pt4: Fixes, Slots, Equip/Stow"

### ISSUE THREAD

**Issue by LarsJandel** [Avindr/MxM-IssueTracking#93]
First of all, thanks for doing this series! 🙏

As another user already mentioned on YouTube:
The _Gameplay Walkthrough Pt4_ provides three scripts via Google Drive, which are causing errors.

CharacterSlotsScripts:
- CharacterInventory.cs
- CharacterModel.cs
- ECharAttachements.cs

Using:
- Unity 2020.2.1f1
- Motion Matching for Unity v2.2.7 - released on December 14, 2020

```
[CompilerError] The type or namespace name 'ObjectManagement' does not exist in the namespace 'AnimationUprising' (are you missing an assembly reference?)
Compiler Error at Assets\Scripts\CharacterModel.cs:2 column 25
1:   using UnityEngine;
-->2:   using AnimationUprising.ObjectManagement;
3:   using System.Collections.Generic;
```

```
[CompilerError] The type or namespace name 'FootstepProfile' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Assets\Scripts\CharacterModel.cs:17 column 34
15:   {
16:       [Header("General")]
-->17:       [SerializeField] private FootstepProfile m_footStepProfile = null;
19:       [Header("Attachment Points")]
```

```
[CompilerError] The type or namespace name 'ObjectPooler' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Assets\Scripts\CharacterModel.cs:22 column 17
20:   [SerializeField] private AttachmentPoint[] m_attachments = null;
-->22:   private ObjectPooler m_objectPooler;
24:   private Dictionary<ECharAttachments, AttachmentPoint> m_attachmentSlots = null;
```

**Comment by Avindr** [comment]
Hi,

Thanks for letting me know. I must have uploaded the wrong version of the
scripts. I'll update them within the next week or so.

Regards,

Ken Claassen

**Comment by LarsJandel** [comment]
Thanks, then I will be able to continue following along the series.

**Comment by Avindr** [comment]
I've uploaded the full set of scripts that I currently have for the demo. They aren't all used yet in the walkthrough tutorial but at least they shouldn't cause errors now: 

https://drive.google.com/file/d/1aC-fMOv5UTQz0oo7s0Zbcuwu2nHsdTii/view?usp=sharing

**Comment by LarsJandel** [comment]
Thanks so much!
