### ISSUE TITLE
MxM Timeline UI for dark theme

### ISSUE THREAD

**Issue by slik** [Avindr/MxM-IssueTracking#99]
Nothing special, just small UI bug

![image](https://user-images.githubusercontent.com/98554/106401759-82c2a680-642e-11eb-9ac9-18692db137e1.png)

**Comment by Avindr** [comment]
Cheer's I'll fix this up for the next time I update.

**Comment by Avindr** [comment]
This is now fixed for the MxM v2.9 releasing soon
